import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,ForeignKey,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class Application(Base):
 __tablename__='applications';__table_args__=(UniqueConstraint('candidate_id','job_id',name='uq_candidate_application_job'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False,index=True);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='RESTRICT'),nullable=False);resume_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('resumes.id',ondelete='RESTRICT'),nullable=False);tailored_resume_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('tailored_resumes.id',ondelete='SET NULL'));application_url:Mapped[str|None]=mapped_column(String(2048));application_method:Mapped[str]=mapped_column(String(30),nullable=False,default='manual');application_source:Mapped[str]=mapped_column(String(100),nullable=False,default='job_source');status:Mapped[str]=mapped_column(String(30),nullable=False,default='draft');notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class ApplicationEvent(Base):
 __tablename__='application_events';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);application_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('applications.id',ondelete='CASCADE'),nullable=False,index=True);event_type:Mapped[str]=mapped_column(String(50),nullable=False);from_status:Mapped[str|None]=mapped_column(String(30));to_status:Mapped[str|None]=mapped_column(String(30));note:Mapped[str|None]=mapped_column(Text);metadata_json:Mapped[dict|None]=mapped_column(JSONB);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
