import uuid
from datetime import datetime, timezone
from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

class HiringSource(Base):
 __tablename__='hiring_sources';__table_args__=(UniqueConstraint('normalized_name','source_type',name='uq_hiring_source_name_type'),)
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);name:Mapped[str]=mapped_column(String(255),nullable=False);normalized_name:Mapped[str]=mapped_column(String(255),nullable=False,index=True);source_type:Mapped[str]=mapped_column(String(50),nullable=False,index=True);base_url:Mapped[str|None]=mapped_column(String(2048));description:Mapped[str|None]=mapped_column(Text);is_active:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class CompanyHiringSource(Base):
 __tablename__='company_hiring_sources';__table_args__=(UniqueConstraint('company_id','hiring_source_id','normalized_source_url',name='uq_company_hiring_source_url'),)
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);company_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('companies.id',ondelete='CASCADE'),nullable=False,index=True);hiring_source_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('hiring_sources.id',ondelete='CASCADE'),nullable=False,index=True);source_url:Mapped[str]=mapped_column(String(2048),nullable=False);normalized_source_url:Mapped[str]=mapped_column(String(2048),nullable=False,index=True);external_reference:Mapped[str|None]=mapped_column(String(255));status:Mapped[str]=mapped_column(String(20),nullable=False,default='unknown');confidence:Mapped[str]=mapped_column(String(20),nullable=False,default='low');discovery_method:Mapped[str]=mapped_column(String(50),nullable=False,default='unknown');first_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);last_verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));last_checked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
