import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,ForeignKey,Integer,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class Job(Base):
 __tablename__='jobs';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);company_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('companies.id',ondelete='CASCADE'),nullable=False,index=True);canonical_title:Mapped[str]=mapped_column(String(500),nullable=False);normalized_title:Mapped[str]=mapped_column(String(500),nullable=False,index=True);description:Mapped[str|None]=mapped_column(Text);employment_type:Mapped[str|None]=mapped_column(String(50));seniority:Mapped[str|None]=mapped_column(String(50));workplace_mode:Mapped[str|None]=mapped_column(String(50));department:Mapped[str|None]=mapped_column(String(255));experience_min:Mapped[int|None]=mapped_column(Integer);experience_max:Mapped[int|None]=mapped_column(Integer);application_url:Mapped[str|None]=mapped_column(String(2048));status:Mapped[str]=mapped_column(String(30),nullable=False,default='open');first_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class JobSource(Base):
 __tablename__='job_sources';__table_args__=(UniqueConstraint('company_hiring_source_id','external_job_id',name='uq_job_source_external'),UniqueConstraint('company_hiring_source_id','normalized_source_url',name='uq_job_source_url'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);job_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='SET NULL'),index=True);company_hiring_source_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('company_hiring_sources.id',ondelete='CASCADE'),nullable=False,index=True);external_job_id:Mapped[str|None]=mapped_column(String(255),nullable=True,index=True);source_url:Mapped[str]=mapped_column(String(2048),nullable=False);normalized_source_url:Mapped[str]=mapped_column(String(2048),nullable=False,index=True);source_title:Mapped[str|None]=mapped_column(String(500));source_description:Mapped[str|None]=mapped_column(Text);source_metadata:Mapped[dict|None]=mapped_column(JSONB);status:Mapped[str]=mapped_column(String(30),nullable=False,default='open');first_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class JobLocation(Base):
 __tablename__='job_locations';__table_args__=(UniqueConstraint('job_id','normalized_location',name='uq_job_location'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False,index=True);location_name:Mapped[str]=mapped_column(String(255),nullable=False);normalized_location:Mapped[str]=mapped_column(String(500),nullable=False);area:Mapped[str|None]=mapped_column(String(255));city:Mapped[str|None]=mapped_column(String(255),index=True);country:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
