import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,ForeignKey,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class JobAnalysis(Base):
 __tablename__='job_analyses';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False,index=True);status:Mapped[str]=mapped_column(String(20),nullable=False);analysis_version:Mapped[str]=mapped_column(String(30),nullable=False);model_provider:Mapped[str]=mapped_column(String(50),nullable=False);model_name:Mapped[str|None]=mapped_column(String(100));prompt_version:Mapped[str]=mapped_column(String(30),nullable=False);source_content_hash:Mapped[str]=mapped_column(String(64),nullable=False,index=True);raw_response_hash:Mapped[str|None]=mapped_column(String(64));analyzed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));error_message:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class JobRequirement(Base):
 __tablename__='job_requirements';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);analysis_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('job_analyses.id',ondelete='CASCADE'),nullable=False,index=True);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False,index=True);requirement_type:Mapped[str]=mapped_column(String(50),nullable=False);importance:Mapped[str]=mapped_column(String(30),nullable=False);description:Mapped[str]=mapped_column(Text,nullable=False);normalized_text:Mapped[str]=mapped_column(Text,nullable=False);source_section:Mapped[str|None]=mapped_column(String(100));confidence:Mapped[str]=mapped_column(String(20),nullable=False)
class JobSkill(Base):
 __tablename__='job_skills';__table_args__=(UniqueConstraint('analysis_id','skill_id',name='uq_job_analysis_skill'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);analysis_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('job_analyses.id',ondelete='CASCADE'),nullable=False);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False,index=True);skill_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('skills.id',ondelete='RESTRICT'),nullable=False);importance:Mapped[str]=mapped_column(String(30),nullable=False);evidence_text:Mapped[str]=mapped_column(Text,nullable=False);confidence:Mapped[str]=mapped_column(String(20),nullable=False);source_requirement_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('job_requirements.id',ondelete='SET NULL'))
