import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,ForeignKey,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class Contact(Base):
 __tablename__='contacts';__table_args__=(UniqueConstraint('candidate_id','company_id','normalized_name','job_title',name='uq_candidate_company_contact'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False,index=True);company_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('companies.id',ondelete='CASCADE'),nullable=False,index=True);name:Mapped[str]=mapped_column(String(255),nullable=False);normalized_name:Mapped[str]=mapped_column(String(255),nullable=False);job_title:Mapped[str|None]=mapped_column(String(255));email:Mapped[str|None]=mapped_column(String(255));phone:Mapped[str|None]=mapped_column(String(50));profile_url:Mapped[str|None]=mapped_column(String(2048));source:Mapped[str]=mapped_column(String(50),nullable=False);source_url:Mapped[str|None]=mapped_column(String(2048));contact_type:Mapped[str]=mapped_column(String(50),nullable=False);verification_status:Mapped[str]=mapped_column(String(30),nullable=False,default='unverified');confidence:Mapped[str]=mapped_column(String(20),nullable=False,default='unknown');is_public:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class JobContact(Base):
 __tablename__='job_contacts';__table_args__=(UniqueConstraint('job_id','contact_id',name='uq_job_contact'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False);contact_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('contacts.id',ondelete='CASCADE'),nullable=False);relationship_type:Mapped[str]=mapped_column(String(50),nullable=False);confidence:Mapped[str]=mapped_column(String(20),nullable=False);source:Mapped[str]=mapped_column(String(50),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
class Outreach(Base):
 __tablename__='outreach';__table_args__=(UniqueConstraint('candidate_id','job_id','contact_id',name='uq_candidate_job_contact_outreach'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False,index=True);company_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('companies.id',ondelete='RESTRICT'),nullable=False);job_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='SET NULL'));application_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('applications.id',ondelete='SET NULL'));contact_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey('contacts.id',ondelete='SET NULL'));channel:Mapped[str]=mapped_column(String(50),nullable=False);subject:Mapped[str]=mapped_column(String(500),nullable=False);body:Mapped[str]=mapped_column(Text,nullable=False);call_to_action:Mapped[str|None]=mapped_column(String(500));draft_method:Mapped[str]=mapped_column(String(30),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default='draft');approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));sent_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc),nullable=False)
class OutreachEvent(Base):
 __tablename__='outreach_events';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);outreach_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('outreach.id',ondelete='CASCADE'),nullable=False,index=True);event_type:Mapped[str]=mapped_column(String(50),nullable=False);from_status:Mapped[str|None]=mapped_column(String(30));to_status:Mapped[str|None]=mapped_column(String(30));metadata_json:Mapped[dict|None]=mapped_column(JSONB);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
