import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,ForeignKey,Integer,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class CandidatePreference(Base):
 __tablename__='candidate_preferences';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),unique=True,nullable=False);job_search_active:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False);work_modes:Mapped[str|None]=mapped_column(Text);employment_types:Mapped[str|None]=mapped_column(Text);target_seniority:Mapped[str|None]=mapped_column(Text);min_experience_years:Mapped[int|None]=mapped_column(Integer);max_experience_years:Mapped[int|None]=mapped_column(Integer);min_salary:Mapped[int|None]=mapped_column(Integer);max_salary:Mapped[int|None]=mapped_column(Integer);salary_currency:Mapped[str|None]=mapped_column(String(10));salary_period:Mapped[str|None]=mapped_column(String(20));relocation_preference:Mapped[str|None]=mapped_column(String(20));company_preferences:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc));updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc))
class PreferenceLocation(Base):
 __tablename__='candidate_preference_locations';__table_args__=(UniqueConstraint('candidate_preference_id','normalized_name',name='uq_preference_location'),);id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_preference_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidate_preferences.id',ondelete='CASCADE'),nullable=False);display_name:Mapped[str]=mapped_column(String(255),nullable=False);normalized_name:Mapped[str]=mapped_column(String(255),nullable=False);is_primary:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False)
