import uuid
from datetime import datetime, timezone
from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base
class Skill(Base):
 __tablename__='skills'; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); name:Mapped[str]=mapped_column(String(255),nullable=False); normalized_name:Mapped[str]=mapped_column(String(255),unique=True,index=True,nullable=False); description:Mapped[str|None]=mapped_column(Text); category:Mapped[str]=mapped_column(String(80),nullable=False); is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc))
class SkillAlias(Base):
 __tablename__='skill_aliases'; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); skill_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('skills.id',ondelete='CASCADE'),nullable=False); alias:Mapped[str]=mapped_column(String(255),nullable=False); normalized_alias:Mapped[str]=mapped_column(String(255),unique=True,index=True,nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc))
class CandidateSkill(Base):
 __tablename__='candidate_skills'; __table_args__=(UniqueConstraint('candidate_id','skill_id',name='uq_candidate_skill'),); id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False); skill_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('skills.id',ondelete='RESTRICT'),nullable=False); proficiency:Mapped[str|None]=mapped_column(String(20)); years_experience:Mapped[int|None]=mapped_column(Integer); is_primary:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),onupdate=lambda:datetime.now(timezone.utc))
class SkillEvidence(Base):
 __tablename__='skill_evidence'; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); candidate_skill_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidate_skills.id',ondelete='CASCADE'),nullable=False); evidence_type:Mapped[str]=mapped_column(String(30),nullable=False); reference_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); description:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc))
