import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,ForeignKey,String,Text
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
class TailoredResume(Base):
 __tablename__='tailored_resumes';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);candidate_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False,index=True);job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False);resume_selection_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('resume_selections.id',ondelete='RESTRICT'),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,default='review_required');generation_version:Mapped[int]=mapped_column(nullable=False,default=1);template_version:Mapped[str]=mapped_column(String(30),nullable=False,default='1.0');source_hash:Mapped[str]=mapped_column(String(64),nullable=False);structured_content:Mapped[dict]=mapped_column(JSONB,nullable=False);validation_summary:Mapped[dict]=mapped_column(JSONB,nullable=False);document_status:Mapped[str]=mapped_column(String(30),nullable=False,default='pending');document_storage_key:Mapped[str|None]=mapped_column(String(500));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));rejected_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));rejection_reason:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
class TailoredResumeClaim(Base):
 __tablename__='tailored_resume_claims';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4);tailored_resume_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey('tailored_resumes.id',ondelete='CASCADE'),nullable=False,index=True);claim_text:Mapped[str]=mapped_column(Text,nullable=False);source_type:Mapped[str]=mapped_column(String(30),nullable=False);source_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc),nullable=False)
