import {Component, inject} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {CompaniesService, Company, CompanyDraft, CompanyLocation, DiscoveryRun} from './companies.service';import {HiringSourcesService,HiringSource} from './hiring-sources.service';

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<main><h1>Company discovery</h1><p>Save companies you know about; this page does not claim that a company is hiring.</p><section><h2>Discover user-provided companies</h2><label>Location <input [(ngModel)]="location.location_name" required></label><label>Area <input [(ngModel)]="location.area"></label><label>City <input [(ngModel)]="location.city"></label><button (click)="discover()" [disabled]="loading">{{loading?'Discovering…':'Record company discovery'}}</button><p *ngIf="message">{{message}}</p></section><section><h2>Add company</h2><label>Name <input [(ngModel)]="draft.name" required></label><label>Website <input [(ngModel)]="draft.website_url" placeholder="https://example.com"></label><label>Location <input [(ngModel)]="draftLocation.location_name"></label><label>City <input [(ngModel)]="draftLocation.city"></label><button (click)="add()">Add company</button></section><section><h2>Companies found</h2><label>Search <input [(ngModel)]="search" (keyup.enter)="load()"></label><button (click)="load()">Search</button><p *ngIf="loading">Loading…</p><p *ngIf="error">{{error}}</p><p *ngIf="!loading&&!error&&!companies.length">No companies found. Add a verified company manually to begin.</p><ul><li *ngFor="let company of companies"><button (click)="view(company.id)">{{company.canonical_name}}</button><span *ngIf="company.website_domain"> — {{company.website_domain}}</span><span> · confidence: {{company.confidence}}</span></li></ul></section><section *ngIf="selected"><h2>{{selected.canonical_name}}</h2><p *ngIf="selected.website_url"><a [href]="selected.website_url" target="_blank" rel="noopener">{{selected.website_domain || selected.website_url}}</a></p><p *ngIf="selected.description">{{selected.description}}</p><p *ngIf="selected.industry">Industry: {{selected.industry}}</p><h3>Locations</h3><p *ngIf="!selected.locations.length">No locations recorded.</p><ul><li *ngFor="let item of selected.locations">{{item.location_name}}<span *ngIf="item.city">, {{item.city}}</span></li></ul></section><section><h2>Recent discovery runs</h2><p *ngIf="!runs.length">No discovery runs yet.</p><ul><li *ngFor="let run of runs">{{run.location_name}} — {{run.provider_name}} — {{run.status}} ({{run.result_count}} companies)</li></ul></section></main>`})
export class CompaniesComponent {
  private api=inject(CompaniesService); private sourcesApi=inject(HiringSourcesService); companies:Company[]=[]; runs:DiscoveryRun[]=[]; sources:HiringSource[]=[]; selected?:Company; loading=false; error=''; message=''; search=''; location:CompanyLocation={location_name:''}; draft:CompanyDraft={name:'',locations:[]}; draftLocation:CompanyLocation={location_name:''};
  constructor(){this.load();this.loadRuns()}
  load(){this.loading=true;this.error='';this.api.list(this.search).subscribe({next:x=>{this.companies=x;this.loading=false},error:()=>{this.error='Unable to load companies. Sign in and try again.';this.loading=false}})}
  loadRuns(){this.api.runs().subscribe({next:x=>this.runs=x})}
  discover(){if(!this.location.location_name){this.message='A location is required.';return}this.loading=true;this.api.discover(this.location,[]).subscribe({next:x=>{this.message=`${x.run.status}: ${x.run.result_count} companies found.`;this.companies=x.companies;this.loading=false;this.loadRuns()},error:()=>{this.message='Unable to record discovery.';this.loading=false}})}
  add(){if(!this.draft.name){this.message='Company name is required.';return}this.draft.locations=this.draftLocation.location_name?[this.draftLocation]:[];this.api.create(this.draft).subscribe({next:company=>{this.message='Company saved.';this.draft={name:'',locations:[]};this.draftLocation={location_name:''};this.view(company.id);this.load()},error:()=>this.message='Unable to save company. Check the URL and required fields.'})}
  view(id:string){this.api.get(id).subscribe({next:x=>{this.selected=x;this.sourcesApi.list(id).subscribe({next:s=>this.sources=s})},error:()=>this.message='Unable to load company details.'})}
}
