"""contact management and outreach
Revision ID: 20261004_21
Revises: 20261004_20
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20261004_21';down_revision='20261004_20';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('contacts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('company_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(255),nullable=False),sa.Column('normalized_name',sa.String(255),nullable=False),sa.Column('job_title',sa.String(255)),sa.Column('email',sa.String(255)),sa.Column('phone',sa.String(50)),sa.Column('profile_url',sa.String(2048)),sa.Column('source',sa.String(50),nullable=False),sa.Column('source_url',sa.String(2048)),sa.Column('contact_type',sa.String(50),nullable=False),sa.Column('verification_status',sa.String(30),nullable=False),sa.Column('confidence',sa.String(20),nullable=False),sa.Column('is_public',sa.Boolean,nullable=False),sa.Column('notes',sa.Text),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','company_id','normalized_name','job_title',name='uq_candidate_company_contact'))
 op.create_table('job_contacts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False),sa.Column('contact_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('contacts.id',ondelete='CASCADE'),nullable=False),sa.Column('relationship_type',sa.String(50),nullable=False),sa.Column('confidence',sa.String(20),nullable=False),sa.Column('source',sa.String(50),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('job_id','contact_id',name='uq_job_contact'))
 op.create_table('outreach',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('company_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('companies.id',ondelete='RESTRICT'),nullable=False),sa.Column('job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('jobs.id',ondelete='SET NULL')),sa.Column('application_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('applications.id',ondelete='SET NULL')),sa.Column('contact_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('contacts.id',ondelete='SET NULL')),sa.Column('channel',sa.String(50),nullable=False),sa.Column('subject',sa.String(500),nullable=False),sa.Column('body',sa.Text,nullable=False),sa.Column('call_to_action',sa.String(500)),sa.Column('draft_method',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('sent_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','job_id','contact_id',name='uq_candidate_job_contact_outreach'))
 op.create_table('outreach_events',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('outreach_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('outreach.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.String(50),nullable=False),sa.Column('from_status',sa.String(30)),sa.Column('to_status',sa.String(30)),sa.Column('metadata_json',postgresql.JSONB),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():op.drop_table('outreach_events');op.drop_table('outreach');op.drop_table('job_contacts');op.drop_table('contacts')
