"""job discovery
Revision ID: 20261004_11
Revises: 20261004_10
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='20261004_11';down_revision='20261004_10';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('jobs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('company_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('canonical_title',sa.String(500),nullable=False),sa.Column('normalized_title',sa.String(500),nullable=False),sa.Column('description',sa.Text),sa.Column('employment_type',sa.String(50)),sa.Column('seniority',sa.String(50)),sa.Column('workplace_mode',sa.String(50)),sa.Column('department',sa.String(255)),sa.Column('experience_min',sa.Integer),sa.Column('experience_max',sa.Integer),sa.Column('application_url',sa.String(2048)),sa.Column('status',sa.String(30),nullable=False),sa.Column('first_seen_at',sa.DateTime(timezone=True),nullable=False),sa.Column('last_seen_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_jobs_company_id','jobs',['company_id']);op.create_index('ix_jobs_normalized_title','jobs',['normalized_title'])
 op.create_table('job_sources',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('jobs.id',ondelete='SET NULL')),sa.Column('company_hiring_source_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('company_hiring_sources.id',ondelete='CASCADE'),nullable=False),sa.Column('external_job_id',sa.String(255)),sa.Column('source_url',sa.String(2048),nullable=False),sa.Column('normalized_source_url',sa.String(2048),nullable=False),sa.Column('source_title',sa.String(500)),sa.Column('source_description',sa.Text),sa.Column('source_metadata',postgresql.JSONB),sa.Column('status',sa.String(30),nullable=False),sa.Column('first_seen_at',sa.DateTime(timezone=True),nullable=False),sa.Column('last_seen_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('company_hiring_source_id','external_job_id',name='uq_job_source_external'),sa.UniqueConstraint('company_hiring_source_id','normalized_source_url',name='uq_job_source_url'))
 op.create_table('job_locations',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('jobs.id',ondelete='CASCADE'),nullable=False),sa.Column('location_name',sa.String(255),nullable=False),sa.Column('normalized_location',sa.String(500),nullable=False),sa.Column('area',sa.String(255)),sa.Column('city',sa.String(255)),sa.Column('country',sa.String(255)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('job_id','normalized_location',name='uq_job_location'))
def downgrade():op.drop_table('job_locations');op.drop_table('job_sources');op.drop_table('jobs')
