"""communications and email integrations
Revision ID: 20261004_22
Revises: 20261004_21
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision='20261004_22'; down_revision='20261004_21'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('integrations',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('provider',sa.String(30),nullable=False),sa.Column('integration_type',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('external_account_id',sa.String(255)),sa.Column('external_email',sa.String(255)),sa.Column('scopes',postgresql.JSONB),sa.Column('credential_reference',sa.String(255)),sa.Column('last_sync_at',sa.DateTime(timezone=True)),sa.Column('sync_cursor',sa.String(1024)),sa.Column('last_error',sa.String(1000)),sa.Column('connected_at',sa.DateTime(timezone=True)),sa.Column('disconnected_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','provider','external_account_id',name='uq_candidate_email_integration'));op.create_index('ix_integrations_candidate_id','integrations',['candidate_id'])
 op.create_table('email_threads',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('provider',sa.String(30),nullable=False),sa.Column('external_thread_id',sa.String(255),nullable=False),sa.Column('subject',sa.String(500)),sa.Column('normalized_subject',sa.String(500)),sa.Column('first_message_at',sa.DateTime(timezone=True)),sa.Column('last_message_at',sa.DateTime(timezone=True)),sa.Column('message_count',sa.Integer,nullable=False),sa.Column('company_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('companies.id',ondelete='SET NULL')),sa.Column('job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('jobs.id',ondelete='SET NULL')),sa.Column('application_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('applications.id',ondelete='SET NULL')),sa.Column('contact_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('contacts.id',ondelete='SET NULL')),sa.Column('outreach_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('outreach.id',ondelete='SET NULL')),sa.Column('association_method',sa.String(30),nullable=False),sa.Column('association_confidence',sa.String(20),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','provider','external_thread_id',name='uq_candidate_provider_thread'));op.create_index('ix_email_threads_candidate_id','email_threads',['candidate_id'])
 op.create_table('email_messages',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('thread_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('email_threads.id',ondelete='CASCADE'),nullable=False),sa.Column('integration_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('integrations.id',ondelete='CASCADE'),nullable=False),sa.Column('provider',sa.String(30),nullable=False),sa.Column('external_message_id',sa.String(255),nullable=False),sa.Column('external_thread_id',sa.String(255),nullable=False),sa.Column('from_email',sa.String(255)),sa.Column('from_name',sa.String(255)),sa.Column('to_emails',postgresql.JSONB),sa.Column('subject',sa.String(500)),sa.Column('sent_at',sa.DateTime(timezone=True)),sa.Column('received_at',sa.DateTime(timezone=True)),sa.Column('direction',sa.String(20),nullable=False),sa.Column('snippet',sa.String(1000)),sa.Column('body_text',sa.Text),sa.Column('has_attachments',sa.Boolean,nullable=False),sa.Column('classification',sa.String(50),nullable=False),sa.Column('classification_confidence',sa.String(20),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('candidate_id','provider','external_message_id',name='uq_candidate_provider_message'));op.create_index('ix_email_messages_candidate_id','email_messages',['candidate_id']);op.create_index('ix_email_messages_thread_id','email_messages',['thread_id']);op.create_index('ix_email_messages_integration_id','email_messages',['integration_id']);op.create_index('ix_email_messages_received_at','email_messages',['received_at'])
 op.create_table('communication_events',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('candidate_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('candidates.id',ondelete='CASCADE'),nullable=False),sa.Column('email_message_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('email_messages.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.String(50),nullable=False),sa.Column('event_at',sa.DateTime(timezone=True),nullable=False),sa.Column('metadata_json',postgresql.JSONB),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False));op.create_index('ix_communication_events_candidate_id','communication_events',['candidate_id']);op.create_index('ix_communication_events_email_message_id','communication_events',['email_message_id'])
def downgrade():
 op.drop_table('communication_events');op.drop_table('email_messages');op.drop_table('email_threads');op.drop_table('integrations')
